# ensure you've activated enp0s3 which is the default iface name in Virtualbox using nmtui
# ensure you've mounted the VirtualBox Guest Addition via VirtualBox GUI
---
- hosts: target
  become: true

  tasks:

  - name: Finished
    debug:
      msg: "Installation finished! go to http://{{ inventory_hostname }}"
