# ensure you've activated enp0s3 which is the default iface name in Virtualbox using nmtui
# ensure you've mounted the VirtualBox Guest Addition via VirtualBox GUI
---
- hosts: target
  become: true
  tasks:

  - name: Get number of CPU's
    shell: lscpu | grep "CPU(s)" | head -1 | awk '{ print $2 }'
    register: cpu_count

  - name: Get number of Total Memory
    shell: awk '/MemTotal/ {print $2}' /proc/meminfo
    register: mem_size

  - block: 
       - name: "Minimal requirements tests"
         debug:
            msg: "Not enough CPU, exiting... CPU count: {{ cpu_count }}"
       - meta: end_play
    when: 
       - cpu_count|int == 1
       - mem_size < 6144

  - name: Mount VirtualBox Guest Addition CDROM
    mount:
      path: /mnt/
      src: /dev/cdrom
      fstype: iso9660
      opts: ro,noauto
      state: mounted

  - name: upgrade all packages
    yum: name=* state=latest

  - name: install epel release
    yum:
      name: epel-release

  - name: install package dependecies for VirtualBox Guest and AWX build
    yum:
      name: bzip2, kernel-headers, kernel-devel, gcc, make, git, python-pip, ansible, python-devel

  - name: check if vboxguest is loaded
    shell: lsmod | grep vboxguest | cut -d ' ' -f 1
    register: lsmod_result

  - name: install VirtualBox Guest Addition
    shell: ./VBoxLinuxAdditions.run
    args:
      chdir: /mnt/
    when: lsmod_result.stdout != 'vboxguest'

  - name: quick setup for VirtualBox
    shell: /sbin/rcvboxadd quicksetup all
    when: lsmod_result.stdout != 'vboxguest'

  - name: install latest Docker from docker.com
    shell: curl -fsSL https://get.docker.com/ | sh

  - name: upgrade to the latest pip version
    pip:
     name: pip
     extra_args: --upgrade

  - name: install docker using pip for AWX build
    pip:
      name: docker, docker-compose, more-itertools<=5.0.0

  - name: add HTTP in public zone for AWX
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: add HTTPS in public zone for AWX
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: add HTTPS rule in public zone for AWX
    firewalld:
      service: https
      permanent: yes
      state: enabled
      zone: public
      immediate: yes

  - name: add HTTPS rule in public zone for AWX
    firewalld:
      service: http
      permanent: yes
      state: enabled
      zone: public
      immediate: yes
  
  - name: Create docker group
    group:
      name: docker
      state: present

  - name: add ansible-security in docker group for AWX install
    user:
      name: ansible-security
      group: docker
      append: yes

  - name: turn on dockerd service and start on boot
    systemd:
      state: started
      name: docker
      enabled: yes

  - name: clone AWX repo 
    git:
      repo: https://github.com/ansible/awx
      dest: ~/awx
    become: no

  - name: run the install playbook for AWX
    shell: ansible-playbook -i inventory install.yml
    args:
      chdir: /home/ansible-security/awx/installer/
    become: yes

  - name: Unmount VirtualBox Guest Addition CDROM
    mount:
      path: /mnt/
      src: /dev/cdrom
      state: absent

  - name: Finished
    debug:
      msg: "Installation finished! go to http://{{ inventory_hostname }}"

